### ISSUE TITLE
Adding an additional source directory leads to error

### ISSUE THREAD

**Issue by heliotrip** [hdorgeval/cucumber-ts-starter#2]
The issue is that, at least when running zsh on macOS, if you add additional source directories to the project, the wildcards in the cucumber-js command line are expanded, leading the cucumber interpreter to believe that the additional source files are actually feature files.  

For example, as a part of transitioning to my own project, I added an additional directory under domains, and added .ts files into that directory:

```
domains/simple-maths
domains/simple-maths/simple-maths-calculator.ts
domains/chinsay
domains/chinsay/workspace.ts

```

Although npm run build reported no errors, running npm test reported errors like:

```
tardis (cjn) ~/src/Chinsay/cucumber-ts-starter ± ./node_modules/.bin/cucumber-js features/**/*.feature --logLevel=verbose --require build/**/*.js --require step-definitions/**/*.ts --require hooks/**/*.ts  --require-module ts-node/register --format-options '{"snippetInterface": "async-await"}' --format json:reports/cucumber-report.json --format summary
Error: (1:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got '"use strict";'
    at /Users/cjn/src/Chinsay/cucumber-ts-starter/node_modules/cucumber/src/cli/helpers.js:63:13
    at Array.forEach (<anonymous>)
    at /Users/cjn/src/Chinsay/cucumber-ts-starter/node_modules/cucumber/src/cli/helpers.js:51:10
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/Users/cjn/src/Chinsay/cucumber-ts-starter/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Users/cjn/src/Chinsay/cucumber-ts-starter/node_modules/bluebird/js/release/generators.js:97:49)
    at /Users/cjn/src/Chinsay/cucumber-ts-starter/node_modules/bluebird/js/release/generators.js:201:15
    at getTestCases (/Users/cjn/src/Chinsay/cucumber-ts-starter/node_modules/cucumber/lib/cli/helpers.js:96:18)
    at /Users/cjn/src/Chinsay/cucumber-ts-starter/node_modules/cucumber/src/cli/helpers.js:30:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/Users/cjn/src/Chinsay/cucumber-ts-starter/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Users/cjn/src/Chinsay/cucumber-ts-starter/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/Users/cjn/src/Chinsay/cucumber-ts-starter/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/cjn/src/Chinsay/cucumber-ts-starter/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/cjn/src/Chinsay/cucumber-ts-starter/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/cjn/src/Chinsay/cucumber-ts-starter/node_modules/bluebird/js/release/async.js:133:16)
[1]    94694 exit 1     ./node_modules/.bin/cucumber-js features/**/*.feature --logLevel=verbose     

```

The fix is straightforward: add quotes around the paths, so that cucumber itself performs the wildcard expansion, i.e. in package.json, replace 

`"cucumber": "./node_modules/.bin/cucumber-js features/**/*.feature --logLevel=error --require step-definitions/**/*.ts --require hooks/**/*.ts  --require-module ts-node/register --format-options '{\"snippetInterface\": \"async-await\"}' --format json:reports/cucumber-report.json --format summary",`

with:

`"cucumber": "./node_modules/.bin/cucumber-js features/**/*.feature --logLevel=error --require 'step-definitions/**/*.ts' --require 'hooks/**/*.ts'  --require-module ts-node/register --format-options '{\"snippetInterface\": \"async-await\"}' --format json:reports/cucumber-report.json --format summary",
`

Pull request coming.

**Comment by hdorgeval** [comment]
Hi @heliotrip, thank you for your feedback and work. I have published a brand new version of this project and you can use it as a template instead of cloning the repo.
